### PR TITLE
more debug information for socket

### PR DESCRIPTION
**Pull request by FredyC**
Just making those debug information more helpful as it's very easy to get lost when trying stuff with multiple clients.

### CODE REVIEW

**Comment by defunctzombie** [comment]
PR is old. Closing.

**Comment by FredyC** [comment]
@defunctzombie Well I am wondering why there was no response from maintainers to this...

**Comment by defunctzombie** [comment]
@FredyC the PR should be rebased on latest master.

**Comment by FredyC** [comment]
@defunctzombie And should I do that? I mean this PR was sitting here for half a year without anybody noticing  If I rebase it, will you merge it?

**Comment by defunctzombie** [comment]
@FredyC if you think the debug info really helps, yes. I don't feel strongly about it but am also not against the changes so will merge them.

**Pull request closed without merging**
